### ISSUE TITLE
Crash on Startup with missing Images

### ISSUE THREAD

**Issue by newhinton** [PaulWoitaschek/Voice#1153]
I am currently experiencing crashes on startup

```
2022-02-25 00:51:34.098 29556-29556/de.ph1b.audiobook_debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.ph1b.audiobook_debug, PID: 29556
    android.content.res.Resources$NotFoundException: Drawable de.ph1b.audiobook_debug:drawable/album_art with resource ID #0x7f07005d
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/album_art.xml from drawable resource ID #0x7f07005d
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:891)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673)
        at android.content.res.Resources.loadDrawable(Resources.java:993)
        ...
        at coil.RealImageLoader.execute(RealImageLoader.kt:133)
        at de.ph1b.audiobook.playback.session.ChangeNotifier.updateMetadata(ChangeNotifier.kt:119)
        at de.ph1b.audiobook.playback.session.PlaybackService$onCreate$1$2.emit(PlaybackService.kt:126)
        at de.ph1b.audiobook.playback.session.PlaybackService$onCreate$1$2.emit(PlaybackService.kt:125)
        at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(Distinct.kt:81)
        ...
        Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at android.content.res.ResourcesImpl.loadComplexColor(ResourcesImpl.java:1065)
        at android.content.res.Resources.loadComplexColor(Resources.java:1147)
        at android.content.res.TypedArray.getComplexColor(TypedArray.java:565)
        at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:2043)
        at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1990)
        at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:836)
2022-02-25 00:51:34.098 29556-29556/de.ph1b.audiobook_debug E/AndroidRuntime:     at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:734)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:954)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:877)
        	... 39 more
        
```

I assume this is due to the media scanner not having read the image yet. I can reproduce this by adding an folder, waiting for the books to show up and start playing one while others are still loading and no image has been added. After that, the app becomes completely unusable and does not recover.

**Comment by PaulWoitaschek** [comment]
With which version is this happening?

**Comment by newhinton** [comment]
commit 49fa3076903a47ad3909a40d71e3068dc896b967

On my main device, Lineageos 18.1

**Comment by PaulWoitaschek** [comment]
Hmm this makes no sense to me. Maybe this is somehow specific to lineage? This does not happen on Api level 28. I've seen this crash before but that was already fixed:
https://github.com/PaulWoitaschek/Voice/commit/2f3a85a0bb742b4caef4bd07d15e9a22a2fb44ac

But this commit is before yours
