### ISSUE TITLE
App crash on adding an audiobook folder (6.0.0-alpha15)

### ISSUE THREAD

**Issue by shirish87** [PaulWoitaschek/Voice#1210]
Version: 6.0.0-alpha15
OS: Android 11

First use. App crash after adding an audiobook folder.

Audiobooks are listed fine after reopening the app, although grid view doesn't display embedded m4b book covers.

Stacktrace:
```
04-25 18:50:18.068 14017 14017 D AndroidRuntime: Shutting down VM
04-25 18:50:18.070 14017 14017 E AndroidRuntime: FATAL EXCEPTION: main
04-25 18:50:18.070 14017 14017 E AndroidRuntime: Process: de.ph1b.audiobook, PID: 14017
04-25 18:50:18.070 14017 14017 E AndroidRuntime: java.lang.IllegalStateException: Place was called on a node which was placed already
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:895)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:79)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:266)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:407)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:406)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:333)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place$default(Placeable.kt:191)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.material3.MinimumTouchTargetModifier$measure$1.invoke(TouchTarget.kt:83)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.material3.MinimumTouchTargetModifier$measure$1.invoke(TouchTarget.kt:80)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:333)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:179)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.foundation.layout.FillModifier$measure$1.invoke(Size.kt:663)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.foundation.layout.FillModifier$measure$1.invoke(Size.kt:662)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:333)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:160)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.access$placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:28)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:146)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:145)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:122)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:112)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:59)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:145)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM$default(Placeable.kt:286)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.foundation.lazy.grid.LazyGridPositionedItem.place(LazyMeasuredItem.kt:212)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.foundation.lazy.grid.LazyGridMeasureKt$measureLazyGrid$3.invoke(LazyGridMeasure.kt:254)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.foundation.lazy.grid.LazyGridMeasureKt$measureLazyGrid$3.invoke(LazyGridMeasure.kt:253)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:333)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.foundation.lazy.grid.LazyGridMeasureResult.placeChildren(Unknown Source:2)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:593)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:939)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:924)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:122)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:112)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:52)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:924)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:909)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:79)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:266)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:407)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:406)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:333)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:315)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:158)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.access$placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:28)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:146)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:145)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:122)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:112)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:59)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:145)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:170)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:797)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:280)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:38)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:208)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:740)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.node.Owner$DefaultImpls.measureAndLayout$default(Owner.kt:196)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:937)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at android.view.View.draw(View.java:22357)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21230)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.070 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21190)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8186)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:811)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7701)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-25 18:50:18.071 14017 14017 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
04-25 18:50:18.330 14017 14056 D TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
```

**Comment by PaulWoitaschek** [comment]
Is this still happening with the latest beta?

**Comment by shirish87** [comment]
Can confirm that this issue has been fixed. Cover images take a while to show in the list and grid views, but they load alright! Thanks!
