### ISSUE TITLE
Bluetooth Crash on play

### ISSUE THREAD

**Issue by bendmunk95** [PaulWoitaschek/Voice#1701]
### Overview

Tested 7.0.0-1 on two devices running Android 10. All devices will crash the system Bluetooth if it is turned on, regardless of it's connected state.

### How to reproduce

1. Turn on Bluetooth, connecting a device is not necessary.
2. Open an audio book and press play.
3. Android error message pops up "Bluetooth unexpectedly quit working"

### Version

7.0.0-1

### Android Version

10

### Device Model

Pixel 3 XL, Galaxy Note9

**Comment by PaulWoitaschek** [comment]
Can you send a bug report?
https://developer.android.com/studio/debug/bug-report

**Comment by bendmunk95** [comment]
Sent via email

**Comment by PaulWoitaschek** [comment]
Exception in bug report:
```java
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.android.bluetooth, PID: 6766
E AndroidRuntime: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: voice.data.ChapterMark
E AndroidRuntime: 	at android.os.Parcel.readParcelableCreator(Parcel.java:3059)
E AndroidRuntime: 	at android.os.Parcel.readParcelable(Parcel.java:2981)
E AndroidRuntime: 	at android.os.Parcel.readParcelableArray(Parcel.java:3094)
E AndroidRuntime: 	at android.os.Parcel.readValue(Parcel.java:2937)
E AndroidRuntime: 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
E AndroidRuntime: 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
E AndroidRuntime: 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
E AndroidRuntime: 	at android.os.Bundle.putAll(Bundle.java:292)
E AndroidRuntime: 	at com.android.bluetooth.avrcp.Util.descriptionToBundle(Util.java:114)
E AndroidRuntime: 	at com.android.bluetooth.avrcp.Util.toMetadata(Util.java:177)
E AndroidRuntime: 	at com.android.bluetooth.avrcp.Util.toMetadataList(Util.java:254)
E AndroidRuntime: 	at com.android.bluetooth.avrcp.MediaPlayerWrapper.wrap(MediaPlayerWrapper.java:122)
E AndroidRuntime: 	at com.android.bluetooth.avrcp.MediaPlayerList.addMediaPlayer(MediaPlayerList.java:543)
E AndroidRuntime: 	at com.android.bluetooth.avrcp.MediaPlayerList$4.onAddressedPlayerChanged(MediaPlayerList.java:798)
E AndroidRuntime: 	at android.media.session.MediaSessionManager$CallbackImpl$3.run(MediaSessionManager.java:1115)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by PaulWoitaschek** [comment]
@bendmunk95 

Can you try if this fix works?

https://drive.google.com/file/d/1DRX_GA2sPFzdzxdZKh1s1tAsQpqW0PjI/view?usp=sharing

**Comment by bendmunk95** [comment]
Still same issue 😢. Let me know if you want more bug reports.

**Comment by PaulWoitaschek** [comment]
Please try this, but I'm pretty confident it's working:
https://drive.google.com/file/d/1mJ7N-VR49KcCylnMPDKLz8TylXSeon4B/view?usp=sharing

**Comment by bendmunk95** [comment]
Working now, nice job. Thanks!
