### ISSUE TITLE
Android nags me about Voice repeatedly crashing

### ISSUE THREAD

**Issue by ghost** [PaulWoitaschek/Voice#2347]
### Overview

A dialog appears after my phone turned on this morning, Android wants to send crash report, this is in details:

	android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 267 SQLITE_CORRUPT_VTAB)
		at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
		at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
		at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
		at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
		at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:755)
		at W2.b.h(Unknown Source:2)
		at R2.B.i(Unknown Source:8)
		at w4.h2.a(Unknown Source:192)
		at w4.h2.call(Unknown Source:250)
		at R2.f.w(Unknown Source:5)
		at u6.a.p(Unknown Source:8)
		at Q6.J.run(Unknown Source:112)
		at i.K.run(Unknown Source:178)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
		at java.lang.Thread.run(Thread.java:1012)
		Suppressed: W6.g: [v0{Cancelling}@48b9bac, Dispatchers.IO]

Voice does not start when I tried to launch it after. Clearing cache does not help. Clearing all data fixed it.

### How to reproduce

1. No idea, I just turned my phone on.

### Version

8.2.3

### Android Version

33

### Device Model

M2101K6G

**Comment by PaulWoitaschek** [comment]
Uff, that's bad. That sounds rather like your phone's memory is corrupted. Does it persist when you reinstall?

**Comment by gwarser** [comment]
It works after I cleared the application data.

My phone is set to turn off for the night, can shutting down interrupt save process and corrupt the database?

Also, I very often see that Voice want to connect to internet (I have it blocked), does it try to send some crash/bug reports, or is this just analytics?
