### ISSUE TITLE
App crashing when loading a particular audiobook

### ISSUE THREAD

**Issue by bvanteru** [PaulWoitaschek/Voice#725]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: OnePlus 5T
Android Version: 7.1.1

After adding a particular single audiobook and closing the audiobook folders view, the app crashes. The crash persists after reopening the application. I have not noticed this issue with other audiobooks.

Here is the exception in logcat.
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6891)
    at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1083)
    at android.view.ViewGroup.invalidateChild(ViewGroup.java:5205)
    at android.view.View.invalidateInternal(View.java:13656)
    at android.view.View.invalidate(View.java:13620)
    at android.view.View.invalidate(View.java:13604)
    at de.ph1b.audiobook.uitools.SquareProgressView$$special$$inlined$observable$1.afterChange(Delegates.kt:66)
    at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:36)
    at de.ph1b.audiobook.uitools.SquareProgressView.setColor(SquareProgressView.kt)
    at de.ph1b.audiobook.features.bookOverview.list.BookShelfHolder$bindCover$1.doResume(BookShelfHolder.kt:89)
    at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
    at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
    at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

I modified the invalidate to run in the main loop and that seems to fix the issue.

**Comment by bvanteru** [comment]
This issue is only when running latest from master and not in the version released to app store.

**Comment by PaulWoitaschek** [comment]
Thanks, needs to be fixed anyways. Don't expect master to be stable. Only the tagged releases are.

**Comment by travisfw** [comment]
I'm having this problem. I reached the end of a chapter and it crashed, and now every time I touch to open that book Voice crashes. I installed from F-Droid and am on the latest release: 5.0.2. Galaxy Tab S6; Android 10.

**Comment by travisfw** [comment]
Interestingly, I pressed play on the widget and it played for a fraction of a second? (Maybe a crash in the background?) I pressed play again on the widget and it played! Then I opened the app and I could play the book. I guess it got past the crash point?

**Comment by mcejp** [comment]
> I pressed play again on the widget and it played! Then I opened the app and I could play the book. I guess it got past the crash point?

Worked for me as well! Thanks <3
