### ISSUE TITLE
Cannot open large Audiobook m4b-file

### ISSUE THREAD

**Issue by githtz** [PaulWoitaschek/Voice#749]
When I add an audiobook that has a large file (in this case: m4b, 2,1GB) the audiobook is not shown in Voice.

App-Version: 3.6.1
Phone Name: LG G3 D855
Android Version: Android 8.1

I've extracted the following log via logcat:

```
[...]
08-17 09:59:39.231 16758 17180 W zygote  : Throwing OutOfMemoryError "Failed to allocate a 47318424 byte allocation with 25165824 free bytes and 32MB until OOM, max allowed footprint 192875960, growth limit 201326592"
08-17 09:59:39.231 16758 17180 I zygote  : Starting a blocking GC Alloc
08-17 09:59:39.231 16758 17180 I zygote  : Starting a blocking GC Alloc
08-17 09:59:39.271 16758 17180 I zygote  : Alloc concurrent copying GC freed 8(47KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 159MB/183MB, paused 176us total 38.920ms
08-17 09:59:39.271 16758 17180 I zygote  : Starting a blocking GC Alloc
08-17 09:59:39.312 16758 17180 I zygote  : Alloc concurrent copying GC freed 5(32KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 159MB/183MB, paused 126us total 40.930ms
08-17 09:59:39.312 16758 17180 I zygote  : Forcing collection of SoftReferences for 45MB allocation
08-17 09:59:39.312 16758 17180 I zygote  : Starting a blocking GC Alloc
08-17 09:59:39.360 16758 17180 I zygote  : Alloc concurrent copying GC freed 8(32KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 159MB/183MB, paused 145us total 47.031ms
08-17 09:59:39.360 16758 17180 W zygote  : Throwing OutOfMemoryError "Failed to allocate a 47318424 byte allocation with 25165824 free bytes and 32MB until OOM, max allowed footprint 192892344, growth limit 201326592"
08-17 09:59:39.360 16758 17180 E LoadTask: OutOfMemory error loading stream
08-17 09:59:39.360 16758 17180 E LoadTask: java.lang.OutOfMemoryError: Failed to allocate a 47318424 byte allocation with 25165824 free bytes and 32MB until OOM, max allowed footprint 192892344, growth limit 201326592
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:370)
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:383)
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:318)
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:309)
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:175)
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
08-17 09:59:39.360 16758 17180 E LoadTask:      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
08-17 09:59:39.360 16758 17180 E LoadTask:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-17 09:59:39.360 16758 17180 E LoadTask:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-17 09:59:39.360 16758 17180 E LoadTask:      at java.lang.Thread.run(Thread.java:764)
[...]
```

Any ideas on this?

**Comment by gwarser** [comment]
https://github.com/PaulWoitaschek/Voice/issues/636

**Comment by githtz** [comment]
@gwarser Ouch, I didn't see that one. But is that really the same problem since in my case I cannot even see the audiobook in Voice, but in #636 it can be seen at least?

**Comment by gwarser** [comment]
Then maybe https://github.com/PaulWoitaschek/Voice/issues/217 ?
