### ISSUE TITLE
Inconsistent Data

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#798]
I have this crash I can't make sense of. Any idea how that could happen?

cc @Plastix 

```
Fatal Exception: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.util.NoSuchElementException: Collection contains no element matching the predicate.
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:496)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:334)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:326)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:575)
       at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.drain(ObservableSwitchMap.java:211)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onError(ObservableSwitchMap.java:140)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:115)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:470)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:330)
       at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:31)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap.subscribeActual(ObservableSwitchMap.java:51)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged.subscribeActual(ObservableDistinctUntilChanged.java:35)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
       at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:108)
       at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:37)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.Observable.subscribe(Observable.java:12183)
       at io.reactivex.Observable.subscribe(Observable.java:12085)
       at de.ph1b.audiobook.features.widget.TriggerWidgetOnChange.init(TriggerWidgetOnChange.kt:26)
       at de.ph1b.audiobook.injection.App.onCreate(App.kt:79)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6517)
       at android.app.ActivityThread.-wrap2(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by Plastix** [comment]
Sorry for the late reply but thanks for tagging me. I've run into this exact issue in production. The problem is that `TriggerWidgetOnChange` is subscribing to an RxJava stream but not providing an error callback. For some reason one of these streams is erroring (probably bad data format):
https://github.com/PaulWoitaschek/Voice/blob/7ac054aa4ac6fa8deb33451576518cc0333bdceb/app/src/main/java/de/ph1b/audiobook/features/widget/TriggerWidgetOnChange.kt#L24-L30
and the subscriber cannot handle said error.

PR incoming to fix this.

**Comment by PaulWoitaschek** [comment]
The subscriber should not handle the error as there should be no error.

You should only handle onError if you expect an error.
Here there is an underlying bug which needs to be fixed so catching this hides the actual bug.

A [Book](https://github.com/PaulWoitaschek/Voice/blob/master/data/src/main/java/de/ph1b/audiobook/data/Book.kt) validates its internal state.
`BookContent` validates that the current chapter specified in the `BookSettings` is present in the chapter list.

Therefore it means that the acutal issue is in the persistence layer.
It is somehow happening that a book (which is always valid as it validates its own state) gets persisted and then when retrieving it is invalid.

But I don't understand how this can happen.
https://github.com/PaulWoitaschek/Voice/blob/master/data/src/main/java/de/ph1b/audiobook/data/repo/internals/BookStorage.kt#L54
This runs in a sql transaction so it should be only committed after all insets are made.

**Comment by Plastix** [comment]
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
```
This is a Kotlin exception right? I would think this is coming from the `find` in `BookRepository`:
https://github.com/PaulWoitaschek/Voice/blob/7ac054aa4ac6fa8deb33451576518cc0333bdceb/app/src/main/java/de/ph1b/audiobook/features/widget/TriggerWidgetOnChange.kt#L39-L49

https://github.com/PaulWoitaschek/Voice/blob/7ac054aa4ac6fa8deb33451576518cc0333bdceb/data/src/main/java/de/ph1b/audiobook/data/repo/BookRepository.kt#L43-L47

The only problem is that `find()` returns `null` if no elements match the predicate while `first()` throws this very exception.

**Comment by PaulWoitaschek** [comment]
No, find returns null. This is then wrapped in an  `Optional` which is completely fine.
How would this throw?

I was acutally missing a vital path of the stacktrace so you did not have all the info, sorry! for that.

```
Fatal Exception: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.util.NoSuchElementException: Collection contains no element matching the predicate.
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:496)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:334)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:326)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:575)
       at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.drain(ObservableSwitchMap.java:211)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onError(ObservableSwitchMap.java:140)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:115)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:470)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:330)
       at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:31)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableSwitchMap.subscribeActual(ObservableSwitchMap.java:51)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged.subscribeActual(ObservableDistinctUntilChanged.java:35)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
       at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:108)
       at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:37)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12197)
       at io.reactivex.Observable.subscribe(Observable.java:12183)
       at io.reactivex.Observable.subscribe(Observable.java:12085)
       at de.ph1b.audiobook.features.widget.TriggerWidgetOnChange.init(TriggerWidgetOnChange.kt:26)
       at de.ph1b.audiobook.injection.App.onCreate(App.kt:79)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6517)
       at android.app.ActivityThread.-wrap2(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Caused by java.util.NoSuchElementException: Collection contains no element matching the predicate.
       at de.ph1b.audiobook.data.BookContent.(BookContent.kt:47)
       at de.ph1b.audiobook.data.repo.internals.BookStorage$books$$inlined$synchronizedWithIoDispatcher$1.invokeSuspend(BookStorage.kt:104)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

So the important part is:
``
Caused by java.util.NoSuchElementException: Collection contains no element matching the predicate.
       at de.ph1b.audiobook.data.BookContent.(BookContent.kt:47)
```

Here the stacktrace is of cause messed up as `BookContent` only has 42 lines.
Please re-read my analysis with this stack trace in mind.
I am pretty sure here the exception is thrown:
https://github.com/PaulWoitaschek/Voice/blob/7ac054aa4ac6fa8deb33451576518cc0333bdceb/data/src/main/java/de/ph1b/audiobook/data/BookContent.kt#L24

**Comment by Plastix** [comment]
I think the `first()` call is the problem as well. This means that somehow your `book` data and `book settings` data are getting out of sync.

I would add a `try` block to catch this exception, report book data to crashlytics (or elsewhere) and re-throw this exception.
