### ISSUE TITLE
[bug]Maybe because there are too many files?

### ISSUE THREAD

**Issue by WayneShao** [PaulWoitaschek/Voice#817]
**The program will flash back when I drop-down the book list.**
Starting with the **previous version**.

Please include the following details in your bug report:

App-Version : **4.1.1**
Phone Name : **Mi Mix 2s**
Android Version : **9.0**

```java
java.lang.IllegalArgumentException: Progress -0.6029427 must be in [0,1]
	at de.ph1b.audiobook.uitools.SquareProgressView$$special$$inlined$observable$2.afterChange(Delegates.kt:72)
	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
	at de.ph1b.audiobook.uitools.SquareProgressView.setProgress(Unknown Source:11)
	at de.ph1b.audiobook.features.bookOverview.list.BookOverviewHolder.bind(BookOverviewComponent.kt:61)
	at de.ph1b.audiobook.features.bookOverview.list.BookOverviewComponent.onBindViewHolder(BookOverviewComponent.kt:22)
	at de.ph1b.audiobook.features.bookOverview.list.BookOverviewComponent.onBindViewHolder(BookOverviewComponent.kt:14)
	at de.ph1b.audiobook.misc.recyclerComponent.CompositeAdapterHelper.onBindViewHolder(CompositeAdapterHelper.kt:30)
	at de.ph1b.audiobook.misc.recyclerComponent.CompositeListAdapter.onBindViewHolder(CompositeListAdapter.kt:22)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1331)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1075)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1832)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5067)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
	at android.view.Choreographer.doCallbacks(Choreographer.java:877)
	at android.view.Choreographer.doFrame(Choreographer.java:805)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by PaulWoitaschek** [comment]
Still figuring out why this happens.
Worked around as of 8848b53ca3563c339dbe9ce20bb283b3ab76ce54
