### ISSUE TITLE
IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo

### ISSUE THREAD

**Issue by di72nn** [PaulWoitaschek/Voice#995]
Not sure whether this report will be of any use, but here it goes.

**I don't have the problem anymore, so the issue may be closed if it's not something meant to be fixed.**

At some point when going to a next "chapter" the app crashed (I don't remember whether I was using fast-forward/rewind at that moment). After that the app crashed every time I tried to open that particular book (the book is plain mp3s in a folder, if that matters). Crash stacktrace follows.
Pressing the "play" button on the main screen seems to have changed reading position, so the app is no longer crashing.

Here's the crash stacktrace:
```
2020-05-29 01:16:42.814 5946-5946/de.ph1b.audiobook E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.ph1b.audiobook, PID: 5946
    java.lang.IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo
        at com.google.android.material.slider.Slider.validateValues(Slider.java:517)
        at com.google.android.material.slider.Slider.validateConfigurationIfDirty(Slider.java:530)
        at com.google.android.material.slider.Slider.onDraw(Slider.java:1366)
        at android.view.View.draw(View.java:20207)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3318)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3122)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2481)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I'm using version 5.0.2 from F-Droid.

Thanks for developing the app!

**Comment by di72nn** [comment]
It happened again.
A chapter ended normally (no fast-forwarding or rewinding), the app moved to the next chapter (next audio file in the folder) and crashed. Opening the book crashes the app.
Pressing "play" button on the main screen fixed it again.

**Comment by knezi** [comment]
Hi,
I can reproduce this issue. (5.0.2 F-droid version)

**steps to reproduce:**

* play entire mp3 file fulfilling:
  * mp3 file must be over 20 minutes long
  * it must be played fro the beginning (i.e. seeking to 5s before end and playing does not produce crash)
* no speed tweaking necessary (I always use 1x)
* the book preview (with slider, cover, pause button) must be open and display must be on (only for the last few seconds)

**result:**

The slider does not stop at the end of the file, but usually goes a bit beyond (i.e. the file is 25:05 long and the slider stops at 25:07)
Then the crash happens.


I tried it with at least 30 files, happens always (files are purchased online). Happens always.

**Comment by richwalm** [comment]
I believe I'm facing the same issue. Here's my error output.

`java.lang.IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo
	at com.google.android.material.slider.Slider.validateValues(Slider.java:517)
	at com.google.android.material.slider.Slider.validateConfigurationIfDirty(Slider.java:530)
	at com.google.android.material.slider.Slider.onDraw(Slider.java:1366)
	at android.view.View.draw(View.java:21619)
	at android.view.View.updateDisplayListIfDirty(View.java:20488)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
	at android.view.View.updateDisplayListIfDirty(View.java:20479)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20479)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20479)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20479)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20479)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20479)
	at android.view.View.draw(View.java:21348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4425)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21622)
	at com.android.internal.policy.DecorView.draw(DecorView.java:839)
	at android.view.View.updateDisplayListIfDirty(View.java:20488)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3709)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3504)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2841)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1796)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7756)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

**Comment by yesmar12** [comment]
I think I am seeing this also. I am also running version 5.0.2 fdroid, currently testing with other fdroid versions.

**Comment by outreal** [comment]
Hi,
I have this problem too with 5.0.2 from F-Droid on a Google pixel 4a 5g.
No problem with 5.0.1

**Comment by PaulWoitaschek** [comment]
This is fixed in the [latest Beta](https://github.com/PaulWoitaschek/Voice/wiki#how-can-i-join-the-beta)
